version: '2'
services:
  
  db:
    image: mariadb:10.4.24
    restart: always
    env_file:
      - app.env
    volumes:
      - mysql-db-volume:/var/lib/mysql
    networks:
      - backend-network

  web:
    image: apap-registry.cs.ui.ac.id/fairuz.satria/apap-088
    restart: always
    ports:
      - "10088:8080"
    volumes:
      - ./file-storage:/file-storage
      - ./log:/log
    env_file:
      - app.env
    depends_on:
      - db
    networks:
      - frontend-network
      - backend-network
  
  web2:
    image: apap-registry.cs.ui.ac.id/fairuz.satria/apap-129
    restart: always
    ports:
      - "10129:2020"
    volumes:
      - ./file-storage:/file-storage
      - ./log:/log
    env_file:
      - app.env
    depends_on:
      - db
    networks:
      - frontend-network
      - backend-network

volumes:
  mysql-db-volume:

networks:
  frontend-network:
    driver: bridge
  backend-network:

